insert into application_user (version, id, username, firstname, lastname, hashed_password, funds) values (1, '1','user','John', 'Normal','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe', 10.0)
insert into user_roles (user_id, roles) values ('1', 'USER')
insert into application_user (version, id, username, firstname, lastname, hashed_password, funds) values (1, '2','admin','Emma', 'Powerful','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.', 10.0)
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('2', 'ADMIN')

insert into crypto_currency (version, id, name, symbol, last_price) values (1, '1','Bitcoin', 'BTC', 10000.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '2','Ethereum', 'ETH', 1000.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '3','Tether', 'USDT', 1.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '4','BNB', 'BNB', 100.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '5','Solana', 'SOL', 100.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '6','XRP', 'XRP', 100.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '7','USD Coin', 'USDC', 1.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '8','Cardano', 'ADA', 100.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '9','Avalanche', 'AVAX', 100.0)
insert into crypto_currency (version, id, name, symbol, last_price) values (1, '10','Dogecoin', 'DOGE', 100.0)